# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Not your Typical Doctor
tagline:             'Professional Ramblings'
description:         'My site developed in Markdown using <a href="http://jekyllrb.com" target="_blank">Jekyll</a> . '
url:                 http://lanyon.getpoole.com
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Mike Dent
  url:               https://twitter.com/mikedent13
  email:             mike.dent@gmail.com

# Custom vars
version:             0.0.1
